version: '3'
services:
      mica:
              image: obiba/mica
              container_name: mica
              ports:
                      - "8872:8082"
              links:
                      - mongo
                      - agate
                      - opal
              environment:
                      - JAVA_OPTS=-Xmx2G
                      - MICA_ADMINISTRATOR_PASSWORD=${MICA_ADMINISTRATOR_PASSWORD}
                      - MONGO_HOST=mongo
                      - MONGO_PORT=27017
                      - OPAL_URL=http://opal:8080
                      - AGATE_URL=http://agate:8081
              volumes:
                      - ./volumes/mica:/srv
      mongo:
              image: mongo:6.0
              container_name: mongo_6
      opal:
              image: obiba/opal
              container_name: opal
              ports:
                      - "8870:8080"
              links:
                      - mongo
                      - rock
                      - agate
              environment:
                      - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMINISTRATOR_PASSWORD}
                      - MONGO_HOST=mongo
                      - MONGO_PORT=27017
                      - AGATE_URL=http://agate:8081
                      - ROCK_HOSTS=rock:8085
              volumes:
                      - ./volumes/opal:/srv
      rock:
              image: obiba/rock
              container_name: rock
      agate:
              image: obiba/agate
              container_name: agate
              ports:
                      - "8871:8081"
              links:
                      - mongo
              environment:
                      - AGATE_ADMINISTRATOR_PASSWORD=${AGATE_ADMINISTRATOR_PASSWORD}
                      - MONGO_HOST=mongo
                      - MONGO_PORT=27017
                      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
              volumes:
                      - ./volumes/agate:/srv
             
